#############################################################################
# Makefile for building: Elina_Scanner
# Generated by qmake (2.01a) (Qt 4.8.2) on: Tue Mar 12 16:56:35 2013
# Project:  Elina_Scanner.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Elina_Scanner.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = read_label.cpp \
		change_label.cpp \
		sxpf.cpp \
		katastrofi.cpp \
		network_test.cpp \
		apografi.cpp \
		fortosi_new_1a.cpp \
		profortosi_progress_1_2.cpp \
		profortosi_progress_1_1.cpp \
		profortosi_progress_1.cpp \
		profortosi_new_1_2.cpp \
		profortosi_new_1_1.cpp \
		profortosi_new_1_b.cpp \
		profortosi_new_1.cpp \
		profortosi_sel.cpp \
		fortosi_new_1_2.cpp \
		fortosi_progress_1_2.cpp \
		fortosi_progress_1_1.cpp \
		fortosi_progress_1.cpp \
		fortosi_new_1_1.cpp \
		fortosi_new_1_b.cpp \
		fortosi_new_1.cpp \
		fortosi_sel.cpp \
		main.cpp \
		elina_scanner.cpp \
		rewrap_sc.cpp \
		return_roll.cpp moc_read_label.cpp \
		moc_change_label.cpp \
		moc_sxpf.cpp \
		moc_katastrofi.cpp \
		moc_network_test.cpp \
		moc_apografi.cpp \
		moc_fortosi_new_1a.cpp \
		moc_profortosi_progress_1_2.cpp \
		moc_profortosi_progress_1_1.cpp \
		moc_profortosi_progress_1.cpp \
		moc_profortosi_new_1_2.cpp \
		moc_profortosi_new_1_1.cpp \
		moc_profortosi_new_1_b.cpp \
		moc_profortosi_new_1.cpp \
		moc_profortosi_sel.cpp \
		moc_fortosi_new_1_2.cpp \
		moc_fortosi_progress_1_2.cpp \
		moc_fortosi_progress_1_1.cpp \
		moc_fortosi_progress_1.cpp \
		moc_fortosi_new_1_1.cpp \
		moc_fortosi_new_1_b.cpp \
		moc_fortosi_new_1.cpp \
		moc_fortosi_sel.cpp \
		moc_elina_scanner.cpp \
		moc_rewrap_sc.cpp \
		moc_return_roll.cpp
OBJECTS       = read_label.o \
		change_label.o \
		sxpf.o \
		katastrofi.o \
		network_test.o \
		apografi.o \
		fortosi_new_1a.o \
		profortosi_progress_1_2.o \
		profortosi_progress_1_1.o \
		profortosi_progress_1.o \
		profortosi_new_1_2.o \
		profortosi_new_1_1.o \
		profortosi_new_1_b.o \
		profortosi_new_1.o \
		profortosi_sel.o \
		fortosi_new_1_2.o \
		fortosi_progress_1_2.o \
		fortosi_progress_1_1.o \
		fortosi_progress_1.o \
		fortosi_new_1_1.o \
		fortosi_new_1_b.o \
		fortosi_new_1.o \
		fortosi_sel.o \
		main.o \
		elina_scanner.o \
		rewrap_sc.o \
		return_roll.o \
		moc_read_label.o \
		moc_change_label.o \
		moc_sxpf.o \
		moc_katastrofi.o \
		moc_network_test.o \
		moc_apografi.o \
		moc_fortosi_new_1a.o \
		moc_profortosi_progress_1_2.o \
		moc_profortosi_progress_1_1.o \
		moc_profortosi_progress_1.o \
		moc_profortosi_new_1_2.o \
		moc_profortosi_new_1_1.o \
		moc_profortosi_new_1_b.o \
		moc_profortosi_new_1.o \
		moc_profortosi_sel.o \
		moc_fortosi_new_1_2.o \
		moc_fortosi_progress_1_2.o \
		moc_fortosi_progress_1_1.o \
		moc_fortosi_progress_1.o \
		moc_fortosi_new_1_1.o \
		moc_fortosi_new_1_b.o \
		moc_fortosi_new_1.o \
		moc_fortosi_sel.o \
		moc_elina_scanner.o \
		moc_rewrap_sc.o \
		moc_return_roll.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Elina_Scanner.pro
QMAKE_TARGET  = Elina_Scanner
DESTDIR       = 
TARGET        = Elina_Scanner

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_read_label.h ui_change_label.h ui_sxpf.h ui_katastrofi.h ui_apografi.h ui_fortosi_new_1a.h ui_profortosi_progress_1_2.h ui_profortosi_progress_1_1.h ui_profortosi_progress_1.h ui_profortosi_new_1_2.h ui_profortosi_new_1_1.h ui_profortosi_new_1_b.h ui_profortosi_new_1.h ui_profortosi_sel.h ui_fortosi_new_1_2.h ui_fortosi_progress_1_2.h ui_fortosi_progress_1_1.h ui_fortosi_progress_1.h ui_fortosi_new_1_1.h ui_fortosi_new_1_b.h ui_fortosi_new_1.h ui_fortosi_sel.h ui_elina_scanner.h ui_rewrap_sc.h ui_return_roll.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Elina_Scanner.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Elina_Scanner.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Elina_Scanner.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Elina_Scanner1.0.0 || $(MKDIR) .tmp/Elina_Scanner1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Elina_Scanner1.0.0/ && $(COPY_FILE) --parents read_label.h change_label.h sxpf.h katastrofi.h network_test.h apografi.h fortosi_new_1a.h profortosi_progress_1_2.h profortosi_progress_1_1.h profortosi_progress_1.h profortosi_new_1_2.h profortosi_new_1_1.h profortosi_new_1_b.h profortosi_new_1.h profortosi_sel.h fortosi_new_1_2.h fortosi_progress_1_2.h fortosi_progress_1_1.h fortosi_progress_1.h fortosi_new_1_1.h fortosi_new_1_b.h constants.h fortosi_new_1.h fortosi_sel.h elina_scanner.h rewrap_sc.h return_roll.h .tmp/Elina_Scanner1.0.0/ && $(COPY_FILE) --parents read_label.cpp change_label.cpp sxpf.cpp katastrofi.cpp network_test.cpp apografi.cpp fortosi_new_1a.cpp profortosi_progress_1_2.cpp profortosi_progress_1_1.cpp profortosi_progress_1.cpp profortosi_new_1_2.cpp profortosi_new_1_1.cpp profortosi_new_1_b.cpp profortosi_new_1.cpp profortosi_sel.cpp fortosi_new_1_2.cpp fortosi_progress_1_2.cpp fortosi_progress_1_1.cpp fortosi_progress_1.cpp fortosi_new_1_1.cpp fortosi_new_1_b.cpp fortosi_new_1.cpp fortosi_sel.cpp main.cpp elina_scanner.cpp rewrap_sc.cpp return_roll.cpp .tmp/Elina_Scanner1.0.0/ && $(COPY_FILE) --parents read_label.ui change_label.ui sxpf.ui katastrofi.ui apografi.ui fortosi_new_1a.ui profortosi_progress_1_2.ui profortosi_progress_1_1.ui profortosi_progress_1.ui profortosi_new_1_2.ui profortosi_new_1_1.ui profortosi_new_1_b.ui profortosi_new_1.ui profortosi_sel.ui fortosi_new_1_2.ui fortosi_progress_1_2.ui fortosi_progress_1_1.ui fortosi_progress_1.ui fortosi_new_1_1.ui fortosi_new_1_b.ui fortosi_new_1.ui fortosi_sel.ui elina_scanner.ui rewrap_sc.ui return_roll.ui .tmp/Elina_Scanner1.0.0/ && (cd `dirname .tmp/Elina_Scanner1.0.0` && $(TAR) Elina_Scanner1.0.0.tar Elina_Scanner1.0.0 && $(COMPRESS) Elina_Scanner1.0.0.tar) && $(MOVE) `dirname .tmp/Elina_Scanner1.0.0`/Elina_Scanner1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Elina_Scanner1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_read_label.cpp moc_change_label.cpp moc_sxpf.cpp moc_katastrofi.cpp moc_network_test.cpp moc_apografi.cpp moc_fortosi_new_1a.cpp moc_profortosi_progress_1_2.cpp moc_profortosi_progress_1_1.cpp moc_profortosi_progress_1.cpp moc_profortosi_new_1_2.cpp moc_profortosi_new_1_1.cpp moc_profortosi_new_1_b.cpp moc_profortosi_new_1.cpp moc_profortosi_sel.cpp moc_fortosi_new_1_2.cpp moc_fortosi_progress_1_2.cpp moc_fortosi_progress_1_1.cpp moc_fortosi_progress_1.cpp moc_fortosi_new_1_1.cpp moc_fortosi_new_1_b.cpp moc_fortosi_new_1.cpp moc_fortosi_sel.cpp moc_elina_scanner.cpp moc_rewrap_sc.cpp moc_return_roll.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_read_label.cpp moc_change_label.cpp moc_sxpf.cpp moc_katastrofi.cpp moc_network_test.cpp moc_apografi.cpp moc_fortosi_new_1a.cpp moc_profortosi_progress_1_2.cpp moc_profortosi_progress_1_1.cpp moc_profortosi_progress_1.cpp moc_profortosi_new_1_2.cpp moc_profortosi_new_1_1.cpp moc_profortosi_new_1_b.cpp moc_profortosi_new_1.cpp moc_profortosi_sel.cpp moc_fortosi_new_1_2.cpp moc_fortosi_progress_1_2.cpp moc_fortosi_progress_1_1.cpp moc_fortosi_progress_1.cpp moc_fortosi_new_1_1.cpp moc_fortosi_new_1_b.cpp moc_fortosi_new_1.cpp moc_fortosi_sel.cpp moc_elina_scanner.cpp moc_rewrap_sc.cpp moc_return_roll.cpp
moc_read_label.cpp: ui_read_label.h \
		constants.h \
		read_label.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) read_label.h -o moc_read_label.cpp

moc_change_label.cpp: ui_change_label.h \
		constants.h \
		change_label.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) change_label.h -o moc_change_label.cpp

moc_sxpf.cpp: ui_sxpf.h \
		constants.h \
		fortosi_new_1.h \
		ui_fortosi_new_1.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		sxpf.h \
		sxpf.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sxpf.h -o moc_sxpf.cpp

moc_katastrofi.cpp: ui_katastrofi.h \
		constants.h \
		katastrofi.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) katastrofi.h -o moc_katastrofi.cpp

moc_network_test.cpp: constants.h \
		network_test.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) network_test.h -o moc_network_test.cpp

moc_apografi.cpp: ui_apografi.h \
		constants.h \
		apografi.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) apografi.h -o moc_apografi.cpp

moc_fortosi_new_1a.cpp: ui_fortosi_new_1a.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		fortosi_new_1a.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_new_1a.h -o moc_fortosi_new_1a.cpp

moc_profortosi_progress_1_2.cpp: ui_profortosi_progress_1_2.h \
		constants.h \
		profortosi_progress_1_2.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profortosi_progress_1_2.h -o moc_profortosi_progress_1_2.cpp

moc_profortosi_progress_1_1.cpp: ui_profortosi_progress_1_1.h \
		constants.h \
		profortosi_progress_1_1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profortosi_progress_1_1.h -o moc_profortosi_progress_1_1.cpp

moc_profortosi_progress_1.cpp: ui_profortosi_progress_1.h \
		constants.h \
		profortosi_progress_1_1.h \
		ui_profortosi_progress_1_1.h \
		profortosi_progress_1_2.h \
		ui_profortosi_progress_1_2.h \
		profortosi_progress_1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profortosi_progress_1.h -o moc_profortosi_progress_1.cpp

moc_profortosi_new_1_2.cpp: ui_profortosi_new_1_2.h \
		constants.h \
		profortosi_new_1_2.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profortosi_new_1_2.h -o moc_profortosi_new_1_2.cpp

moc_profortosi_new_1_1.cpp: ui_profortosi_new_1_1.h \
		constants.h \
		profortosi_new_1_1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profortosi_new_1_1.h -o moc_profortosi_new_1_1.cpp

moc_profortosi_new_1_b.cpp: ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		constants.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h \
		profortosi_new_1_b.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profortosi_new_1_b.h -o moc_profortosi_new_1_b.cpp

moc_profortosi_new_1.cpp: ui_profortosi_new_1.h \
		constants.h \
		profortosi_new_1_b.h \
		ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h \
		profortosi_new_1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profortosi_new_1.h -o moc_profortosi_new_1.cpp

moc_profortosi_sel.cpp: ui_profortosi_sel.h \
		profortosi_new_1.h \
		ui_profortosi_new_1.h \
		constants.h \
		profortosi_new_1_b.h \
		ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h \
		profortosi_progress_1.h \
		ui_profortosi_progress_1.h \
		profortosi_progress_1_1.h \
		ui_profortosi_progress_1_1.h \
		profortosi_progress_1_2.h \
		ui_profortosi_progress_1_2.h \
		profortosi_sel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profortosi_sel.h -o moc_profortosi_sel.cpp

moc_fortosi_new_1_2.cpp: ui_fortosi_new_1_2.h \
		constants.h \
		fortosi_new_1_2.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_new_1_2.h -o moc_fortosi_new_1_2.cpp

moc_fortosi_progress_1_2.cpp: ui_fortosi_progress_1_2.h \
		constants.h \
		fortosi_progress_1_2.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_progress_1_2.h -o moc_fortosi_progress_1_2.cpp

moc_fortosi_progress_1_1.cpp: ui_fortosi_progress_1_1.h \
		constants.h \
		fortosi_progress_1_1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_progress_1_1.h -o moc_fortosi_progress_1_1.cpp

moc_fortosi_progress_1.cpp: ui_fortosi_progress_1.h \
		constants.h \
		fortosi_progress_1_1.h \
		ui_fortosi_progress_1_1.h \
		fortosi_progress_1_2.h \
		ui_fortosi_progress_1_2.h \
		fortosi_progress_1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_progress_1.h -o moc_fortosi_progress_1.cpp

moc_fortosi_new_1_1.cpp: ui_fortosi_new_1_1.h \
		constants.h \
		fortosi_new_1_1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_new_1_1.h -o moc_fortosi_new_1_1.cpp

moc_fortosi_new_1_b.cpp: ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		constants.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		fortosi_new_1_b.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_new_1_b.h -o moc_fortosi_new_1_b.cpp

moc_fortosi_new_1.cpp: ui_fortosi_new_1.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		sxpf.h \
		ui_sxpf.h \
		fortosi_new_1.h \
		fortosi_new_1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_new_1.h -o moc_fortosi_new_1.cpp

moc_fortosi_sel.cpp: ui_fortosi_sel.h \
		fortosi_new_1.h \
		ui_fortosi_new_1.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		sxpf.h \
		ui_sxpf.h \
		fortosi_progress_1.h \
		ui_fortosi_progress_1.h \
		fortosi_progress_1_1.h \
		ui_fortosi_progress_1_1.h \
		fortosi_progress_1_2.h \
		ui_fortosi_progress_1_2.h \
		fortosi_sel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fortosi_sel.h -o moc_fortosi_sel.cpp

moc_elina_scanner.cpp: ui_elina_scanner.h \
		fortosi_sel.h \
		ui_fortosi_sel.h \
		fortosi_new_1.h \
		ui_fortosi_new_1.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		sxpf.h \
		ui_sxpf.h \
		fortosi_progress_1.h \
		ui_fortosi_progress_1.h \
		fortosi_progress_1_1.h \
		ui_fortosi_progress_1_1.h \
		fortosi_progress_1_2.h \
		ui_fortosi_progress_1_2.h \
		profortosi_sel.h \
		ui_profortosi_sel.h \
		profortosi_new_1.h \
		ui_profortosi_new_1.h \
		profortosi_new_1_b.h \
		ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h \
		profortosi_progress_1.h \
		ui_profortosi_progress_1.h \
		profortosi_progress_1_1.h \
		ui_profortosi_progress_1_1.h \
		profortosi_progress_1_2.h \
		ui_profortosi_progress_1_2.h \
		apografi.h \
		ui_apografi.h \
		katastrofi.h \
		ui_katastrofi.h \
		change_label.h \
		ui_change_label.h \
		read_label.h \
		ui_read_label.h \
		rewrap_sc.h \
		return_roll.h \
		elina_scanner.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) elina_scanner.h -o moc_elina_scanner.cpp

moc_rewrap_sc.cpp: constants.h \
		rewrap_sc.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) rewrap_sc.h -o moc_rewrap_sc.cpp

moc_return_roll.cpp: constants.h \
		return_roll.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) return_roll.h -o moc_return_roll.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_read_label.h ui_change_label.h ui_sxpf.h ui_katastrofi.h ui_apografi.h ui_fortosi_new_1a.h ui_profortosi_progress_1_2.h ui_profortosi_progress_1_1.h ui_profortosi_progress_1.h ui_profortosi_new_1_2.h ui_profortosi_new_1_1.h ui_profortosi_new_1_b.h ui_profortosi_new_1.h ui_profortosi_sel.h ui_fortosi_new_1_2.h ui_fortosi_progress_1_2.h ui_fortosi_progress_1_1.h ui_fortosi_progress_1.h ui_fortosi_new_1_1.h ui_fortosi_new_1_b.h ui_fortosi_new_1.h ui_fortosi_sel.h ui_elina_scanner.h ui_rewrap_sc.h ui_return_roll.h
compiler_uic_clean:
	-$(DEL_FILE) ui_read_label.h ui_change_label.h ui_sxpf.h ui_katastrofi.h ui_apografi.h ui_fortosi_new_1a.h ui_profortosi_progress_1_2.h ui_profortosi_progress_1_1.h ui_profortosi_progress_1.h ui_profortosi_new_1_2.h ui_profortosi_new_1_1.h ui_profortosi_new_1_b.h ui_profortosi_new_1.h ui_profortosi_sel.h ui_fortosi_new_1_2.h ui_fortosi_progress_1_2.h ui_fortosi_progress_1_1.h ui_fortosi_progress_1.h ui_fortosi_new_1_1.h ui_fortosi_new_1_b.h ui_fortosi_new_1.h ui_fortosi_sel.h ui_elina_scanner.h ui_rewrap_sc.h ui_return_roll.h
ui_read_label.h: read_label.ui
	/usr/bin/uic-qt4 read_label.ui -o ui_read_label.h

ui_change_label.h: change_label.ui
	/usr/bin/uic-qt4 change_label.ui -o ui_change_label.h

ui_sxpf.h: sxpf.ui
	/usr/bin/uic-qt4 sxpf.ui -o ui_sxpf.h

ui_katastrofi.h: katastrofi.ui
	/usr/bin/uic-qt4 katastrofi.ui -o ui_katastrofi.h

ui_apografi.h: apografi.ui
	/usr/bin/uic-qt4 apografi.ui -o ui_apografi.h

ui_fortosi_new_1a.h: fortosi_new_1a.ui
	/usr/bin/uic-qt4 fortosi_new_1a.ui -o ui_fortosi_new_1a.h

ui_profortosi_progress_1_2.h: profortosi_progress_1_2.ui
	/usr/bin/uic-qt4 profortosi_progress_1_2.ui -o ui_profortosi_progress_1_2.h

ui_profortosi_progress_1_1.h: profortosi_progress_1_1.ui
	/usr/bin/uic-qt4 profortosi_progress_1_1.ui -o ui_profortosi_progress_1_1.h

ui_profortosi_progress_1.h: profortosi_progress_1.ui
	/usr/bin/uic-qt4 profortosi_progress_1.ui -o ui_profortosi_progress_1.h

ui_profortosi_new_1_2.h: profortosi_new_1_2.ui
	/usr/bin/uic-qt4 profortosi_new_1_2.ui -o ui_profortosi_new_1_2.h

ui_profortosi_new_1_1.h: profortosi_new_1_1.ui
	/usr/bin/uic-qt4 profortosi_new_1_1.ui -o ui_profortosi_new_1_1.h

ui_profortosi_new_1_b.h: profortosi_new_1_b.ui
	/usr/bin/uic-qt4 profortosi_new_1_b.ui -o ui_profortosi_new_1_b.h

ui_profortosi_new_1.h: profortosi_new_1.ui
	/usr/bin/uic-qt4 profortosi_new_1.ui -o ui_profortosi_new_1.h

ui_profortosi_sel.h: profortosi_sel.ui
	/usr/bin/uic-qt4 profortosi_sel.ui -o ui_profortosi_sel.h

ui_fortosi_new_1_2.h: fortosi_new_1_2.ui
	/usr/bin/uic-qt4 fortosi_new_1_2.ui -o ui_fortosi_new_1_2.h

ui_fortosi_progress_1_2.h: fortosi_progress_1_2.ui
	/usr/bin/uic-qt4 fortosi_progress_1_2.ui -o ui_fortosi_progress_1_2.h

ui_fortosi_progress_1_1.h: fortosi_progress_1_1.ui
	/usr/bin/uic-qt4 fortosi_progress_1_1.ui -o ui_fortosi_progress_1_1.h

ui_fortosi_progress_1.h: fortosi_progress_1.ui
	/usr/bin/uic-qt4 fortosi_progress_1.ui -o ui_fortosi_progress_1.h

ui_fortosi_new_1_1.h: fortosi_new_1_1.ui
	/usr/bin/uic-qt4 fortosi_new_1_1.ui -o ui_fortosi_new_1_1.h

ui_fortosi_new_1_b.h: fortosi_new_1_b.ui
	/usr/bin/uic-qt4 fortosi_new_1_b.ui -o ui_fortosi_new_1_b.h

ui_fortosi_new_1.h: fortosi_new_1.ui
	/usr/bin/uic-qt4 fortosi_new_1.ui -o ui_fortosi_new_1.h

ui_fortosi_sel.h: fortosi_sel.ui
	/usr/bin/uic-qt4 fortosi_sel.ui -o ui_fortosi_sel.h

ui_elina_scanner.h: elina_scanner.ui
	/usr/bin/uic-qt4 elina_scanner.ui -o ui_elina_scanner.h

ui_rewrap_sc.h: rewrap_sc.ui
	/usr/bin/uic-qt4 rewrap_sc.ui -o ui_rewrap_sc.h

ui_return_roll.h: return_roll.ui
	/usr/bin/uic-qt4 return_roll.ui -o ui_return_roll.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

read_label.o: read_label.cpp read_label.h \
		ui_read_label.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o read_label.o read_label.cpp

change_label.o: change_label.cpp change_label.h \
		ui_change_label.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o change_label.o change_label.cpp

sxpf.o: sxpf.cpp sxpf.h \
		ui_sxpf.h \
		constants.h \
		fortosi_new_1.h \
		ui_fortosi_new_1.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sxpf.o sxpf.cpp

katastrofi.o: katastrofi.cpp katastrofi.h \
		ui_katastrofi.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o katastrofi.o katastrofi.cpp

network_test.o: network_test.cpp network_test.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network_test.o network_test.cpp

apografi.o: apografi.cpp apografi.h \
		ui_apografi.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o apografi.o apografi.cpp

fortosi_new_1a.o: fortosi_new_1a.cpp fortosi_new_1a.h \
		ui_fortosi_new_1a.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_new_1a.o fortosi_new_1a.cpp

profortosi_progress_1_2.o: profortosi_progress_1_2.cpp profortosi_progress_1_2.h \
		ui_profortosi_progress_1_2.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profortosi_progress_1_2.o profortosi_progress_1_2.cpp

profortosi_progress_1_1.o: profortosi_progress_1_1.cpp profortosi_progress_1_1.h \
		ui_profortosi_progress_1_1.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profortosi_progress_1_1.o profortosi_progress_1_1.cpp

profortosi_progress_1.o: profortosi_progress_1.cpp profortosi_progress_1.h \
		ui_profortosi_progress_1.h \
		constants.h \
		profortosi_progress_1_1.h \
		ui_profortosi_progress_1_1.h \
		profortosi_progress_1_2.h \
		ui_profortosi_progress_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profortosi_progress_1.o profortosi_progress_1.cpp

profortosi_new_1_2.o: profortosi_new_1_2.cpp profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profortosi_new_1_2.o profortosi_new_1_2.cpp

profortosi_new_1_1.o: profortosi_new_1_1.cpp profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profortosi_new_1_1.o profortosi_new_1_1.cpp

profortosi_new_1_b.o: profortosi_new_1_b.cpp profortosi_new_1_b.h \
		ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		constants.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profortosi_new_1_b.o profortosi_new_1_b.cpp

profortosi_new_1.o: profortosi_new_1.cpp profortosi_new_1.h \
		ui_profortosi_new_1.h \
		constants.h \
		profortosi_new_1_b.h \
		ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profortosi_new_1.o profortosi_new_1.cpp

profortosi_sel.o: profortosi_sel.cpp profortosi_sel.h \
		ui_profortosi_sel.h \
		profortosi_new_1.h \
		ui_profortosi_new_1.h \
		constants.h \
		profortosi_new_1_b.h \
		ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h \
		profortosi_progress_1.h \
		ui_profortosi_progress_1.h \
		profortosi_progress_1_1.h \
		ui_profortosi_progress_1_1.h \
		profortosi_progress_1_2.h \
		ui_profortosi_progress_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profortosi_sel.o profortosi_sel.cpp

fortosi_new_1_2.o: fortosi_new_1_2.cpp fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_new_1_2.o fortosi_new_1_2.cpp

fortosi_progress_1_2.o: fortosi_progress_1_2.cpp fortosi_progress_1_2.h \
		ui_fortosi_progress_1_2.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_progress_1_2.o fortosi_progress_1_2.cpp

fortosi_progress_1_1.o: fortosi_progress_1_1.cpp fortosi_progress_1_1.h \
		ui_fortosi_progress_1_1.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_progress_1_1.o fortosi_progress_1_1.cpp

fortosi_progress_1.o: fortosi_progress_1.cpp fortosi_progress_1.h \
		ui_fortosi_progress_1.h \
		constants.h \
		fortosi_progress_1_1.h \
		ui_fortosi_progress_1_1.h \
		fortosi_progress_1_2.h \
		ui_fortosi_progress_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_progress_1.o fortosi_progress_1.cpp

fortosi_new_1_1.o: fortosi_new_1_1.cpp fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_new_1_1.o fortosi_new_1_1.cpp

fortosi_new_1_b.o: fortosi_new_1_b.cpp fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		constants.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_new_1_b.o fortosi_new_1_b.cpp

fortosi_new_1.o: fortosi_new_1.cpp fortosi_new_1.h \
		ui_fortosi_new_1.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		sxpf.h \
		ui_sxpf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_new_1.o fortosi_new_1.cpp

fortosi_sel.o: fortosi_sel.cpp fortosi_sel.h \
		ui_fortosi_sel.h \
		fortosi_new_1.h \
		ui_fortosi_new_1.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		sxpf.h \
		ui_sxpf.h \
		fortosi_progress_1.h \
		ui_fortosi_progress_1.h \
		fortosi_progress_1_1.h \
		ui_fortosi_progress_1_1.h \
		fortosi_progress_1_2.h \
		ui_fortosi_progress_1_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fortosi_sel.o fortosi_sel.cpp

main.o: main.cpp elina_scanner.h \
		ui_elina_scanner.h \
		fortosi_sel.h \
		ui_fortosi_sel.h \
		fortosi_new_1.h \
		ui_fortosi_new_1.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		sxpf.h \
		ui_sxpf.h \
		fortosi_progress_1.h \
		ui_fortosi_progress_1.h \
		fortosi_progress_1_1.h \
		ui_fortosi_progress_1_1.h \
		fortosi_progress_1_2.h \
		ui_fortosi_progress_1_2.h \
		profortosi_sel.h \
		ui_profortosi_sel.h \
		profortosi_new_1.h \
		ui_profortosi_new_1.h \
		profortosi_new_1_b.h \
		ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h \
		profortosi_progress_1.h \
		ui_profortosi_progress_1.h \
		profortosi_progress_1_1.h \
		ui_profortosi_progress_1_1.h \
		profortosi_progress_1_2.h \
		ui_profortosi_progress_1_2.h \
		apografi.h \
		ui_apografi.h \
		katastrofi.h \
		ui_katastrofi.h \
		change_label.h \
		ui_change_label.h \
		read_label.h \
		ui_read_label.h \
		rewrap_sc.h \
		return_roll.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

elina_scanner.o: elina_scanner.cpp elina_scanner.h \
		ui_elina_scanner.h \
		fortosi_sel.h \
		ui_fortosi_sel.h \
		fortosi_new_1.h \
		ui_fortosi_new_1.h \
		constants.h \
		fortosi_new_1_b.h \
		ui_fortosi_new_1_b.h \
		fortosi_new_1_1.h \
		ui_fortosi_new_1_1.h \
		fortosi_new_1_2.h \
		ui_fortosi_new_1_2.h \
		sxpf.h \
		ui_sxpf.h \
		fortosi_progress_1.h \
		ui_fortosi_progress_1.h \
		fortosi_progress_1_1.h \
		ui_fortosi_progress_1_1.h \
		fortosi_progress_1_2.h \
		ui_fortosi_progress_1_2.h \
		profortosi_sel.h \
		ui_profortosi_sel.h \
		profortosi_new_1.h \
		ui_profortosi_new_1.h \
		profortosi_new_1_b.h \
		ui_profortosi_new_1_b.h \
		profortosi_new_1_1.h \
		ui_profortosi_new_1_1.h \
		profortosi_new_1_2.h \
		ui_profortosi_new_1_2.h \
		profortosi_progress_1.h \
		ui_profortosi_progress_1.h \
		profortosi_progress_1_1.h \
		ui_profortosi_progress_1_1.h \
		profortosi_progress_1_2.h \
		ui_profortosi_progress_1_2.h \
		apografi.h \
		ui_apografi.h \
		katastrofi.h \
		ui_katastrofi.h \
		change_label.h \
		ui_change_label.h \
		read_label.h \
		ui_read_label.h \
		rewrap_sc.h \
		return_roll.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o elina_scanner.o elina_scanner.cpp

rewrap_sc.o: rewrap_sc.cpp rewrap_sc.h \
		constants.h \
		ui_rewrap_sc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rewrap_sc.o rewrap_sc.cpp

return_roll.o: return_roll.cpp return_roll.h \
		constants.h \
		ui_return_roll.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o return_roll.o return_roll.cpp

moc_read_label.o: moc_read_label.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_read_label.o moc_read_label.cpp

moc_change_label.o: moc_change_label.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_change_label.o moc_change_label.cpp

moc_sxpf.o: moc_sxpf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sxpf.o moc_sxpf.cpp

moc_katastrofi.o: moc_katastrofi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_katastrofi.o moc_katastrofi.cpp

moc_network_test.o: moc_network_test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_network_test.o moc_network_test.cpp

moc_apografi.o: moc_apografi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_apografi.o moc_apografi.cpp

moc_fortosi_new_1a.o: moc_fortosi_new_1a.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_new_1a.o moc_fortosi_new_1a.cpp

moc_profortosi_progress_1_2.o: moc_profortosi_progress_1_2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profortosi_progress_1_2.o moc_profortosi_progress_1_2.cpp

moc_profortosi_progress_1_1.o: moc_profortosi_progress_1_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profortosi_progress_1_1.o moc_profortosi_progress_1_1.cpp

moc_profortosi_progress_1.o: moc_profortosi_progress_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profortosi_progress_1.o moc_profortosi_progress_1.cpp

moc_profortosi_new_1_2.o: moc_profortosi_new_1_2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profortosi_new_1_2.o moc_profortosi_new_1_2.cpp

moc_profortosi_new_1_1.o: moc_profortosi_new_1_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profortosi_new_1_1.o moc_profortosi_new_1_1.cpp

moc_profortosi_new_1_b.o: moc_profortosi_new_1_b.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profortosi_new_1_b.o moc_profortosi_new_1_b.cpp

moc_profortosi_new_1.o: moc_profortosi_new_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profortosi_new_1.o moc_profortosi_new_1.cpp

moc_profortosi_sel.o: moc_profortosi_sel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profortosi_sel.o moc_profortosi_sel.cpp

moc_fortosi_new_1_2.o: moc_fortosi_new_1_2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_new_1_2.o moc_fortosi_new_1_2.cpp

moc_fortosi_progress_1_2.o: moc_fortosi_progress_1_2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_progress_1_2.o moc_fortosi_progress_1_2.cpp

moc_fortosi_progress_1_1.o: moc_fortosi_progress_1_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_progress_1_1.o moc_fortosi_progress_1_1.cpp

moc_fortosi_progress_1.o: moc_fortosi_progress_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_progress_1.o moc_fortosi_progress_1.cpp

moc_fortosi_new_1_1.o: moc_fortosi_new_1_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_new_1_1.o moc_fortosi_new_1_1.cpp

moc_fortosi_new_1_b.o: moc_fortosi_new_1_b.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_new_1_b.o moc_fortosi_new_1_b.cpp

moc_fortosi_new_1.o: moc_fortosi_new_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_new_1.o moc_fortosi_new_1.cpp

moc_fortosi_sel.o: moc_fortosi_sel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fortosi_sel.o moc_fortosi_sel.cpp

moc_elina_scanner.o: moc_elina_scanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_elina_scanner.o moc_elina_scanner.cpp

moc_rewrap_sc.o: moc_rewrap_sc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rewrap_sc.o moc_rewrap_sc.cpp

moc_return_roll.o: moc_return_roll.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_return_roll.o moc_return_roll.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

